### ISSUE TITLE
Easy way to change title page needed

### ISSUE THREAD

**Issue by rhb123** [BirkbeckCTP/consortial_billing#21]
I'd like to update the page title at https://www.openlibhums.org/plugins/supporters/signup/ but this isn't possible at present, so a way to easily do this in the system would be appreciated - many thanks

**Comment by joemull** [comment]
Adding this provisionally to the version 1.6 project board, as it is related to OLH's current communications work. This setting can be edited via admin, but it has no name and so cannot be easily searched or opened in the All Settings list on the Manager page.
